services:
  wordpress:
    container_name: wordpress
    image: wordpress:v1
    user: 33:33
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      WP_DB_HOST: mariadb:3306
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
      WP_ADM: ${WP_ADM}
      WP_ADM_PASSWORD: ${WP_ADM_PASSWORD}
      WP_ADM_EMAIL: ${WP_ADM_EMAIL}
      WP_OTH_USER: ${WP_OTH_USER}
      WP_OTH_PASSWORD: ${WP_OTH_PASSWORD}
    volumes:
      - /srv/data/wordpress:/var/www/html/wordpress
    networks:
      - inception_network
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:v1
    depends_on:
      - wordpress
    ports:
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - /srv/data/wordpress:/var/www/html/wordpress:ro
    networks:
      - inception_network
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    image: mariadb:v1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
    volumes:
      - /srv/data/mariadb:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
      
networks:
  inception_network:
    driver: bridge
